### ISSUE TITLE
Hi, when will the code be updated?

### ISSUE THREAD

**Issue by sou6qiu** [ts-kim/RevIN#1]
I have difficulty implementing RevIN on Informer.
I'm confused about what to do with the Decoder input of Informer, so I would like to refer to the official code.

**Comment by ts-kim** [comment]
Thank you for your interest in our work.
We have uploaded the official code.

The training and evaluation codes for Informer will be made available shortly.

**Comment by sou6qiu** [comment]
Hi again.
I appreciate you taking the time to respond to my question.
I've been able to run RevIN on Informer thanks to your code, but I still
have some questions about how RevIN works.
Did you use RevIN after standardization or just remove the standardization
in Informer?
[image: image.png]
I tried both two methods and the latter turned out to be much less
effective than the former. So I wonder how you deal with that.

ts-kim ***@***.***> 于2022年5月17日周二 22:34写道：

**Comment by zhang-potato** [comment]
> I have difficulty implementing RevIN on Informer. I'm confused about what to do with the Decoder input of Informer, so I would like to refer to the official code.

Hello, I would like to ask how you added the RevIN in the Informer. The effect seems to be not obvious after I added it. Can you show me how you added the RevIN? My email is 15993617315@163.com, thank you very much.

**Comment by seharanul17** [comment]
> Hi again. I appreciate you taking the time to respond to my question. I've been able to run RevIN on Informer thanks to your code, but I still have some questions about how RevIN works. Did you use RevIN after standardization or just remove the standardization in Informer? [image: image.png] I tried both two methods and the latter turned out to be much less effective than the former. So I wonder how you deal with that. 

We used RevIN after z-score standardization in Informer. Since instance normalization is employed when RevIN is performed at the input layer, the normalized samples in a batch stay the same regardless of the presence of standardization. However, performance differences can exist because the value of gradients can still be influenced.

**Comment by seharanul17** [comment]
> Hello, I would like to ask how you added the RevIN in the Informer. The effect seems to be not obvious after I added it. Can you show me how you added the RevIN? My email is [15993617315@163.com](mailto:15993617315@163.com), thank you very much.

Hello, thank you for your interest in our work.
We have uploaded the RevIN codes for Informer. Please check it.
