### ISSUE TITLE
作者您好，请教您一个问题

### ISSUE THREAD

**Issue by cdcss** [ts-kim/RevIN#10]
Dear author, I want to ask you a question. Your method uses Z-core normalization in the data processing stage. This normalization method and the method you proposed are used at the same time. What is the difference between your method and this normalization method? Is the difference between two more learnable affine parameters? Are these two parameter values equal to the mean and the variance mentioned in your paper?

**Comment by ts-kim** [comment]
The original Z-score normalization utilizes the statistics of the "training dataset."
RevIN, on the other hand, normalizes the input sequence using the statistics of each individual instance of the "input sequence."
Furthermore, RevIN can be employed as a middle layer within the model. This implies that the statistics used by RevIN can be extracted from the hidden vector sequences.
