### ISSUE TITLE
Is it added correctly

### ISSUE THREAD

**Issue by zhang-potato** [ts-kim/RevIN#2]
I added RevIN in the Informer according to your method, but the effect is not obvious, you can see if I add it correctly

       def forward(self, x_enc, x_mark_enc, x_dec, x_mark_dec, enc_self_mask=None, dec_self_mask=None, dec_enc_mask=None):
                x_enc = self.revin_layer(x=x_enc,mode='norm')
                x_dec = self.revin_layer(x=x_dec,mode='norm')
                enc_out = self.enc_embedding(x_enc, x_mark_enc)
                enc_out, attns = self.encoder(enc_out, attn_mask=enc_self_mask)
                dec_out = self.dec_embedding(x_dec, x_mark_dec)
                dec_out = self.decoder(dec_out, enc_out, x_mask=dec_self_mask, cross_mask=dec_enc_mask)
                dec_out = self.projection(dec_out)
                dec_out = self.revin_layer(x=dec_out,mode='denorm')
                
        
                if self.output_attention:
                    return dec_out[:,-self.pred_len:,:], attns
                else:
                    return dec_out[:,-self.pred_len:,:] # [B, L, D]

**Comment by seharanul17** [comment]
It seems that the line `x_dec = self.revin_layer(x=x_dec,mode='norm')` is unnecessary. The normalization layer should be reversed to see the effect of RevIN. But it has no corresponding denormalization layer in your code. 
Also, we have uploaded the RevIN codes for Informer. Please check the `baselines/Informer2020` folder.
