### ISSUE TITLE
question about the denormalization in DAIN

### ISSUE THREAD

**Issue by robbyyuu** [ts-kim/RevIN#4]
Thank you for such great work. I'm working on time series anomaly detection, and your work has inspired me a lot.
But I have a question about the denormalization in DAIN. You said 

> However, a denormalization step cannot be added to DAIN since it has the Hadamard multiplication operation in the last step, which is not reversible when the input and prediction sequence lengths are different.

 in A.7. But I guess it uses the same gating coefficient $\gamma^{(i)}$ in all timesteps, so it seems to be reversible too, with a corresponding Hadamard (entrywise) division operator.

**Comment by ts-kim** [comment]
We found that DAIN uses the same gating coefficient in all timesteps, as you said.
Therefore, DAIN also can be reversible.
Thank you for your comment.
