### ISSUE TITLE
Hello, I have a question for you

### ISSUE THREAD

**Issue by cdcss** [ts-kim/RevIN#9]
Hello, thank you very much for the code you provided, but I would like to ask, why sometimes adding RevIN in SCINet performs better when the length of the input sequence is different from the length to be predicted for my own data set, but in the same data Under the set, change the length of the input sequence, and the performance of adding RevIN is not good.

**Comment by ts-kim** [comment]
RevIN utilizes the statistics of the input sequence to derive the current distribution of the time series. This implies that the length of the input sequence can impact RevIN's performance. Although we demonstrated in the paper that RevIN is robust to changes in the input sequence length, there may exist an optimal length for capturing the current distribution of the time series. Furthermore, the optimal length may vary across different time series datasets.
